// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyhncywkngzsfsnsobgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5aG5jeXdrbmd6c2ZzbnNvYmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDE0OTQsImV4cCI6MjA1ODExNzQ5NH0.itXrNynkpBX4jae1Pu0KCAjBziKpZTRxT05SVr5dh7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);